server:
  port: 8010
spring:
  application:
    name: feign-learn

feign:
  client:
    config:
      client:
        connectTimeout: 10000
        readTimeout: 30000
        loggerLevel: basic
        retryer:
        encoder:
        decoder:
        errorDecoder:
        requestInterceptors:
  compression:
    request:
      enabled: true
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false

# 没有注册中心时，使用ribbon
feign-learn:
  ribbon:
    listOfServers: http://localhost:8010,http://localhost:8020
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 5000
    ReadTimeout: 20000